[versions]
kotlin = "2.2.21"
spotless = "8.1.0"
detekt = "1.23.8"
dokka = "2.1.0"
quarkus = "3.29.3"
hamcrest-json = "0.3"
mockito-kotlin = "6.1.0"
mockito-inline = "5.2.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
hamcrest-json = { module = "uk.co.datumedge:hamcrest-json", version.ref = "hamcrest-json" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
qute-web = { module = "io.quarkiverse.qute.web:quarkus-qute-web", version = "3.4.4" }
